# Generated by Django 4.0.1 on 2022-02-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAJ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('presupuesto', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinturerias', models.CharField(max_length=40)),
                ('pinturas', models.CharField(max_length=40)),
                ('herramientas', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.CharField(max_length=40)),
                ('especialidades', models.CharField(max_length=40)),
                ('comotrabajamos', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajos_realizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugares', models.CharField(max_length=40)),
                ('obras', models.CharField(max_length=40)),
                ('tiempo', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
